#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Note:
# - Based on wrapper scripts from Anaconda (e.g., ~/anaconda3/envs/nlp-py-3-9/bin/python/pytest).
# - This is currently just used to show path and version info.
#

"""Wrapper for mezcla module info display"""

import re
import sys
from mezcla.__main__ import main as mezcla_main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(mezcla_main())
