#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Note:
# - Based on wrapper scripts from Anaconda (e.g., ~/anaconda3/envs/nlp-py-3-9/bin/python/pytest).
# - This is currently just used to trace out path and version info.
# - A warning is shown if invoked in non-debug mode.
#

"""Wrapper for mezcla module info display"""

import re
import sys
from pathlib import Path

if __name__ == '__main__':
    # Ensure this checkout of mezcla is used (not another installed copy).
    repo_root = str(Path(__file__).resolve().parent.parent)
    sys.path.insert(0, repo_root)

    # Invoke the package entry point in mezcla.__main__.
    from mezcla import debug
    from mezcla.__main__ import main as mezcla_main
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    skip_warnings = debug.debugging()
    sys.exit(mezcla_main(omit_warnings=skip_warnings))
